config/routes.rb
Rails.application.routes.draw do
  resources :people
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:f_name, :m_name, :l_name, :prefix, :address1, :address2, :city, :state, :zipcode, :education, :estimated_income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/_header.html.erb
<%# partial %>
<%# HEADER GOES HERE... <br> %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Data Vis',
    root_path,
    class:"navbar-brand mx-3"
    %>
    <button class="navbar-toggler mx-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse mx-3" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'People',
            people_path,
            class:'nav-link' %>
        </li>
      </ul>
    </div>
</nav>

app/views/home/index.html.erb
<%# load highcharts %>
<%= javascript_include_tag "https://code.highcharts.com/highcharts.js" %>
<%= javascript_include_tag "https://code.highcharts.com/highcharts-3d.js" %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<%# set thousands separator to comma %>
<script>
  Highcharts.setOptions({
      lang: {
          thousandsSep: ','
      }
  });
</script>

<%# header here %>
<h1 class='text-center'>Data Vis Tool</h1>
<div class='text-center'>This app lets you visualize large data sets.</div>
<br>
<div class='text-center'>People Stats:</div>
<br>

<%=
#method to capitalize keys
def capitalize (input)
  #iterate through keys
  input.keys.each do |a|
    b = a.split
    # iterate through each word
    b.each_with_index do |c,i|
      # capitalize word
      b[i] = c.capitalize
      #capitalize letter after backslash
      b[i] = b[i].gsub(/\/[a-z]/) {|s| s.upcase }
    end
    b = b.join(' ')
    input[b] = input[a]
    input.delete(a)
  end
  return input
end

# get education data
education = Person.group(:education).count
education = capitalize(education)
puts education

# get incomes data
incomes = Person.group(:estimated_income).order(:estimated_income).count
incomes=capitalize(incomes)
puts incomes

# get states data
states = capitalize(Person.group(:state).count)
puts states
%>


<div class='container'>
<%# accordion to display data %>
<div id="carouselExampleControls" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="15000">
      <%= pie_chart education,
      id: 'education-chart',
      adapter: "highcharts",
      library: {
        chart: {
          backgroundColor: '#18181b',
          type: 'pie',
          options3d: {
            enabled: true,
            alpha: 25,
            beta: 0
          }
        },
        title: {
          text: 'Education',
          style: {
            color: 'white',
          }
        },
        tooltip: {
          pointFormat: '<b>{point.name}: {point.percentage:.1f}% ({point.y:,.0f})</b>'
        },
        colors: ['#68b7dc', '#6793db', '#6771dc', '#8067dc'],
        plotOptions: {
          pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 40,
            dataLabels: {
              enabled: true,
              format: '{point.name}: {point.percentage:.1f}%',
              style: {
                color: 'white'
              }
            }
          }
        }
      }
      %>
    </div>
    <div class="carousel-item" data-bs-interval="15000">
      <%= pie_chart incomes,
      adapter: "highcharts",
      id: 'incomes-chart',
      library: {
        chart: {
          backgroundColor: '#18181b',
          type: 'pie',
          options3d: {
            enabled: true,
            alpha: 25,
            beta: 0
          }
        },
        title: {
          text: 'Estimated Income',
          style: {
            color: 'white',
          }
        },
        tooltip: {
          pointFormat: '<b>Estimated Income: {point.name}, {point.percentage:.1f}% ({point.y:,.0f})</b>',
          style: {
            # textTransform: 'lowercase'
          }
        },
        colors: ['#68b7dc', '#6793db', '#6771dc', '#8067dc',
        #additional colors - need 4 more; using https://mycolor.space/
        '#D26BCC','#FF967C','#FFC762','#F9F871'
        ],
        plotOptions: {
          pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 40,
            dataLabels: {
              enabled: true,
              format: '{point.name}: {point.percentage:.1f}%',
              style: {
                color: 'white',
                # textTransform: 'lowercase'
              }
            }
          }
        }
      }
      %>
    </div>
    <div class="carousel-item" data-bs-interval="15000">
      <%= pie_chart states,
      adapter: "highcharts",
      id: 'states-chart',
      library: {
        chart: {
          backgroundColor: '#18181b',
          type: 'pie',
          options3d: {
            enabled: true,
            alpha: 25,
            beta: 0
          }
        },
        title: {
          text: 'States',
          style: {
            color: 'white',
          }
        },
        tooltip: {
          pointFormat: '<b>{point.name}: {point.percentage:.1f}% ({point.y:,.0f})</b>'
        },
        # colors: ['#68b7dc', '#6793db', '#6771dc', '#8067dc'],
        plotOptions: {
          pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 40,
            dataLabels: {
              enabled: true,
              format: '{point.name}: {point.percentage:.1f}%',
              style: {
                color: 'white'
              }
            }
          }
        }
      }
      %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

<footer class='text-center mt-5 pt-5 mb-5'>made by <a href='https://github.com/adnjoo'>adnjoo <i class="fab fa-github"></i></a></footer>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <%# Responsive tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag asset_path('data.png') %>

    <!-- Bootstrap CSS + JS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

    <title>Data Visualization</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
  <%= render 'home/header' %>
  <br>
    <%= yield %>

  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name %>
  </div>

  <div class="field">
    <%= form.label :m_name %>
    <%= form.text_field :m_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name %>
  </div>

  <div class="field">
    <%= form.label :prefix %>
    <%= form.text_field :prefix %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.number_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.text_field :education %>
  </div>

  <div class="field">
    <%= form.label :estimated_income %>
    <%= form.text_field :estimated_income %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<%# capitalize method %>
<%=
def capitalize (input)
  input = input.split
  input.each_with_index do |ele, i|
    input[i] = ele.capitalize
    #capitalize letter after backslash
    input[i] = input[i].gsub(/\/[a-z]/) {|s| s.upcase }
    #capitalize names after '
    input[i] = input[i].gsub(/'[a-z]/) {|s| s.upcase }
  end
  return input.join(' ')
end

puts 'input'
%>

<div class='container-fluid'
>
<h4>People</h4>
<div class='table-responsive'>
<table class='table table-striped table-bordered table-hover'>
  <thead class='table-light' style='position: sticky; top: 0;' >
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th style="min-width: 120px">Middle Name</th>
      <th>Last Name</th>
      <th>Prefix</th>
      <th>Address</th>
      <th style="min-width: 120px">Address 2</th>
      <th>City</th>
      <th>State</th>
      <th style="min-width: 100px">Zip Code</th>
      <th>Education</th>
      <th style="min-width: 160px">Estimated Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= person.f_name.capitalize %></td>
        <td><%= person.m_name %></td>
        <td><%= capitalize(person.l_name) %></td>
        <td><%= capitalize(person.prefix) + '.' %></td>
        <td><%= capitalize(person.address1) %></td>
        <td><%= person.address2.capitalize %></td>
        <td><%= capitalize(person.city) %></td>
        <td><%= capitalize(person.state) %></td>
        <td><%= person.zipcode %></td>
        <td><%= capitalize(person.education) %></td>
        <td><%= person.estimated_income.downcase %></td>
        <td><%= link_to 'Show', person %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<%# capitalize method %>
<%=
def capitalize(input)
  input = input.split
  input.each_with_index do |ele, i|
    input[i] = ele.capitalize
    # capitalize names after '
    input[i] = input[i].gsub(/'[a-z]/) {|s| s.upcase }
  end
  return input.join(' ')
end
puts 'input'
%>



<div class="card mt-5 mx-3">
  <div class='card-body'>
    <h1 class='display-4'>
      Name:
      <%= capitalize(@person.f_name) %>
      <%= @person.m_name + '.' %>
      <%= capitalize(@person.l_name) %>,
    </h1>
    <h2>
      Prefix:
      <%= capitalize(@person.prefix) + '.' %>
    </h2>
    <p class='lead'>
      Address:
      <%= capitalize(@person.address2) %>,

      <%= capitalize(@person.address1) %>,
      <br>
      <%= capitalize(@person.city) %>
      <%= capitalize(@person.state) %>,
      <br>
      <%= @person.zipcode %>
    </p>
    <p class='lead'>
      Education level: <%= capitalize(@person.education) %>
      <br>
      Income level: <%= @person.estimated_income.downcase %>
    </p>
  </div>
</div>

<%#= link_to 'Edit', edit_person_path(@person), class:'btn btn-dark' %>
<div style='text-align:center'>
<%= link_to 'Back', people_path, class:'btn btn-secondary d-inline-block m-4' %>
</div>